### ISSUE TITLE
English locale doesn't work

### ISSUE THREAD

**Issue by marcha** [EmmanuelBeziat/parkourfinder#1]
If app is started with locale "en" then we get error Error in render: "TypeError: Cannot read property 'nav' of undefined" 
I found that you miss part "site" in english i18n file
`	"site": {
		"nav": {
			"newspot": "Add a spot",
			"search": "Search",
			"about": "About",
			"settings": "Settings"
		}
	},
`

**Comment by EmmanuelBeziat** [comment]
Hi, thanks.
I’ve fixed the eng json file. :)
